name: build
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.17.x, 1.18.x]
    name: go-build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Build the code
        run: make build
