name: lint

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  golangci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.14.x, 1.15.x]

    name: golangci-lint
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Lint the code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
