name: lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.18.x]
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
